# Apache HTTP Server Deployment - Simple Proxy Version
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-server
  namespace: dev
  labels:
    app: apache-server
    component: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-server
  template:
    metadata:
      labels:
        app: apache-server
        component: web-server
    spec:
      containers:
      - name: apache
        image: httpd:2.4
        ports:
        - containerPort: 80
          name: http
        command: ['sh', '-c']
        args:
        - |
          echo "=== CONFIGURING APACHE PROXY ==="
          
          # Create proxy configuration
          cat > /usr/local/apache2/conf/extra/proxy.conf << 'EOF'
          # Load proxy modules
          LoadModule proxy_module modules/mod_proxy.so
          LoadModule proxy_http_module modules/mod_proxy_http.so
          LoadModule headers_module modules/mod_headers.so
          
          # Proxy to Catalyst service on port 80 (service handles 80->3000 mapping)
          ProxyPreserveHost On
          ProxyPass / http://catalyst-service:80/
          ProxyPassReverse / http://catalyst-service:80/
          
          # Add headers
          Header always set X-Forwarded-Proto "http"
          EOF
          
          # Create httpd.conf
          cat > /usr/local/apache2/conf/httpd.conf << 'EOF'
          ServerRoot "/usr/local/apache2"
          Listen 80
          
          LoadModule mpm_event_module modules/mod_mpm_event.so
          LoadModule authz_core_module modules/mod_authz_core.so
          LoadModule dir_module modules/mod_dir.so
          LoadModule mime_module modules/mod_mime.so
          LoadModule unixd_module modules/mod_unixd.so
          LoadModule log_config_module modules/mod_log_config.so
          
          ServerName apache-server
          
          <IfModule unixd_module>
          User daemon
          Group daemon
          </IfModule>
          
          DocumentRoot "/usr/local/apache2/htdocs"
          
          <Directory />
              AllowOverride None
              Require all denied
          </Directory>
          
          <Directory "/usr/local/apache2/htdocs">
              Options Indexes FollowSymLinks
              AllowOverride None
              Require all granted
          </Directory>
          
          DirectoryIndex index.html
          TypesConfig conf/mime.types
          
          ErrorLog logs/error.log
          LogFormat "%h %l %u %t \"%r\" %>s %b" common
          CustomLog logs/access.log common
          
          # Include proxy configuration
          Include conf/extra/proxy.conf
          EOF
          
          # Test configuration
          echo "Testing Apache configuration..."
          /usr/local/apache2/bin/httpd -t
          
          # Start Apache
          echo "Starting Apache with proxy to Catalyst..."
          exec /usr/local/apache2/bin/httpd -D FOREGROUND
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
      
      restartPolicy: Always

---
# Apache Service
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: dev
  labels:
    app: apache-server
    component: web-server
spec:
  selector:
    app: apache-server
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
  type: NodePort