# ConfigMap for application configuration (non-sensitive only)
apiVersion: v1
kind: ConfigMap
metadata:
  name: rfam-config
  namespace: {{ .Release.Namespace }}
data:
  EBI_PROXY: {{ .Values.EBI_PROXY | quote }}
  PERL5LIB: "/src/RfamWeb:/src/Rfam/Schemata:/src/PfamBase/lib:/src/PfamLib:/src/PfamSchemata"
  RFAMWEB_CONFIG: "/src/RfamWeb/config/rfamweb.conf"
  DBIC_TRACE: "1"
  # Force Apache mode
  USE_APACHE: "1"
  WEB_SERVER: "apache"