apiVersion: v1
kind: Service
metadata:
  name: rfam-website-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: rfam-website
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: apache-proxy
  ports:
  - port: 80
    targetPort: 80
    nodePort: {{ .Values.nodePort }}
  type: NodePort