version: '3.8'
services:
  web:
    build:
      context: ./rfam-website
      dockerfile: Dockerfile
      args:
        - CACHE_BUST=1
        # Uses git clone by default (USE_LOCAL_SOURCE=false)
    volumes:
      - ./config:/src/RfamWeb/config
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - rfam-network

networks:
  rfam-network:
    driver: bridge