version: '3.8'

services:
  # Rfam website
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - CACHE_BUST=1
    volumes:
      - ./config:/src/RfamWeb/config
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - rfam-network

networks:
  rfam-network:
    driver: bridge
