version: '2'

services:
  # Rfam website
  web:
    # build: .
    image: rfam/rfam-website:latest
    volumes:
      - .:/src
      - ./config:/src/RfamWeb/config
    ports:
      - "3000:3000"
    links:
      - db
  # local WebUser database
  db:
    image: mysql:latest
    volumes:
      # create database and tables on startup
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "4406:3306"
