apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-proxy
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-proxy
  template:
    metadata:
      labels:
        app: apache-proxy
    spec:
      containers:
      - name: apache
        image: httpd:2.4
        ports:
        - containerPort: 80
        command: ['sh', '-c']
        args:
        - |
          echo "=== CREATING NUCLEAR SIMPLE APACHE PROXY ==="
          
          # One config file to rule them all
          cat > /usr/local/apache2/conf/httpd.conf << 'EOF'
          ServerRoot "/usr/local/apache2"
          Listen 80
          
          LoadModule mpm_event_module modules/mod_mpm_event.so
          LoadModule authz_core_module modules/mod_authz_core.so
          LoadModule proxy_module modules/mod_proxy.so
          LoadModule proxy_http_module modules/mod_proxy_http.so
          LoadModule headers_module modules/mod_headers.so
          LoadModule unixd_module modules/mod_unixd.so
          
          User daemon
          Group daemon
          ServerName apache-proxy
          
          # Kill everything, proxy everything
          ProxyPass / http://catalyst-service:80/
          ProxyPassReverse / http://catalyst-service:80/
          ProxyPreserveHost On
          
          # Fix the URLs
          RequestHeader set X-Forwarded-Proto "https"
          RequestHeader set X-Forwarded-Host "preview.rfam.org"
          EOF
          
          echo "Apache config created. Testing..."
          /usr/local/apache2/bin/httpd -t
          echo "Starting proxy..."
          exec /usr/local/apache2/bin/httpd -D FOREGROUND

---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: dev
spec:
  selector:
    app: apache-proxy
  ports:
  - port: 80
    targetPort: 80
  type: NodePort