apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-configmap
  namespace: dev
  labels:
    app: rfam-website
    component: apache-config
data:
  rfam-vhost.conf: |
    # Rfam Virtual Host Configuration
    <VirtualHost *:80>
        ServerName rfam-website
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html
        
        # Enable rewrite engine
        RewriteEngine On
        
        # Static content aliases (matching original structure)
        Alias /static /src/RfamWeb/root/static
        Alias /css /src/RfamWeb/root/css  
        Alias /js /src/RfamWeb/root/js
        Alias /images /src/RfamWeb/root/images
        
        # Static directory permissions
        <Directory "/src/RfamWeb/root/static">
            Options -Indexes
            AllowOverride None
            Order allow,deny
            Allow from all
            ExpiresActive On
            ExpiresDefault "access plus 1 month"
            Header set Cache-Control "public, max-age=2592000"
        </Directory>
        
        <Directory "/src/RfamWeb/root">
            Options -Indexes
            AllowOverride None
            Order allow,deny
            Allow from all
        </Directory>
        
        # Proxy configuration for dynamic content
        # Don't proxy static content
        ProxyPass /static !
        ProxyPass /css !
        ProxyPass /js !
        ProxyPass /images !
        
        # CRITICAL: Set proxy headers to tell Catalyst about external URL
        ProxyPreserveHost On
        ProxyPass / http://127.0.0.1:3000/
        ProxyPassReverse / http://127.0.0.1:3000/
        
        # Set headers that Catalyst needs to generate correct URLs
        ProxyPassReverse / http://127.0.0.1:3000/
        Header edit Location ^http://127\.0\.0\.1:3000/ https://preview.rfam.org/
        
        # Add proxy headers for proper URL generation
        <Location />
            ProxyPassReverse http://127.0.0.1:3000/
            # Tell Catalyst what the external scheme and host should be
            RequestHeader set X-Forwarded-Proto "https"
            RequestHeader set X-Forwarded-Host "preview.rfam.org"
            RequestHeader set X-Forwarded-Port "443"
            RequestHeader set X-Original-URI %{REQUEST_URI}e
        </Location>
        
        # Set proxy timeout
        ProxyTimeout 300
        
        # Security headers
        Header always set X-Content-Type-Options nosniff
        Header always set X-Frame-Options SAMEORIGIN
        Header always set X-XSS-Protection "1; mode=block"
        
        # Compression
        <IfModule mod_deflate.c>
            AddOutputFilterByType DEFLATE text/plain
            AddOutputFilterByType DEFLATE text/html
            AddOutputFilterByType DEFLATE text/xml
            AddOutputFilterByType DEFLATE text/css
            AddOutputFilterByType DEFLATE application/xml
            AddOutputFilterByType DEFLATE application/xhtml+xml
            AddOutputFilterByType DEFLATE application/rss+xml
            AddOutputFilterByType DEFLATE application/javascript
            AddOutputFilterByType DEFLATE application/x-javascript
        </IfModule>
        
        # Logging
        ErrorLog logs/rfam_error.log
        CustomLog logs/rfam_access.log combined
        LogLevel info
        
    </VirtualHost>