apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-configmap
  namespace: dev
data:
  proxy.conf: |
    # Minimal Apache proxy to Catalyst
    LoadModule proxy_module modules/mod_proxy.so
    LoadModule proxy_http_module modules/mod_proxy_http.so
    LoadModule headers_module modules/mod_headers.so
    
    # Static files handled by Apache
    Alias /static /src/RfamWeb/root/static
    <Directory "/src/RfamWeb/root/static">
        Require all granted
        ExpiresActive On
        ExpiresDefault "access plus 1 week"
    </Directory>
    
    # Everything else goes to Catalyst
    ProxyPass /static !
    ProxyPass / http://catalyst-service:80/
    ProxyPassReverse / http://catalyst-service:80/
    
    # Tell Catalyst the real external URL
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Host "preview.rfam.org"