# Application configuration
rfam:
  replicas: 1
  image:
    repository: ghcr.io/rfam/rfam-website
    tag: latest
    pullPolicy: Always

# Apache proxy configuration  
apache:
  replicas: 1
  image:
    repository: httpd
    tag: "2.4"

# URL configuration
url:
  hostname: rfam.org

# Database secret
database:
  secretName: db-pro

# Proxy settings
proxy:
  http: http://wwwcache.ebi.ac.uk:3128
  https: http://wwwcache.ebi.ac.uk:3128
  noProxy: localhost,127.0.0.1,rfam-website-service

# Namespace
namespace: prod

# Node port
nodePort: 30083