# Rfam
rfamBranch: master
rfamPort: 3000
rfamReplicas: 1
setEnv: "dev"


#TODO:  Database
DATABASE_HOST: "<SET_ME>"
DATABASE_PORT: "<SET_ME>"
DATABASE_NAME: "<SET_ME>"
DATABASE_USER: "<SET_ME>"
DATABASE_PASSWORD: "<SET_ME>"

EBI_PROXY: "http://hh-wwwcache.ebi.ac.uk:3128"

# Optional: Override default repository
rfamGitRepo: "https://github.com/Rfam/rfam-website.git"
rfamGitBranch: "create-k8s-deployment-for-preview-site" 